org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)


create_version = 6.0.8-289
ponder_version = 1.0.91
flywheel_version = 1.0.5
registrate_version = MC1.20-1.3.3


mapping_channel=official
mapping_version=1.20.1

archives_name=FIB_MOD

mod_id=fib_mod
mod_name=FIB Mod
mod_license=MIT
mod_version=0.1.5-0.1

mod_group_id=com.fib.fib
mod_authors=
mod_description=

jei_version=15.20.0.130
